### ISSUE TITLE
NullPointerException for PlayerInteractEvent

### ISSUE THREAD

**Issue by Andre601** [harry0198/MailMe#6]
Receiving this error when someone (it was you Harolds in this case) joins the server:
```
[08:30:42 ERROR]: Could not pass event PlayerInteractEvent to MailMe v1.3.3
java.lang.NullPointerException: null
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1015) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
        at java.util.regex.Matcher.replaceAll(Matcher.java:1182) ~[?:?]
        at java.lang.String.replaceAll(String.java:2126) ~[?:?]
        at com.haroldstudios.mailme.utility.Utils.applyPlaceHolders(Utils.java:88) ~[?:?]
        at com.haroldstudios.mailme.ui.MailGui.open(MailGui.java:78) ~[?:?]
        at com.haroldstudios.mailme.command.MailCmd.read(MailCmd.java:100) ~[?:?]
        at com.haroldstudios.mailme.events.EntityEvents.onInteract(EntityEvents.java:100) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor443.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-164]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:137) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1324) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-164]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by harry0198** [comment]
Can you send me your config.yml and the player data.json file: 2b4fb8f8-b62b-4623-a777-b80495f92d81 please. I can't seem to reproduce this in any way and my only theory is that your welcome mail is malformed

**Comment by Andre601** [comment]
Config.yml: https://hasteb.in/ibugozaf.yaml
playerdata: https://hasteb.in/abayumeb.json

**Comment by harry0198** [comment]
Okay, I know what the issue is. Update will be out in the morning

**Comment by harry0198** [comment]
Latest version in theory will have fixed this: https://www.spigotmc.org/resources/mailme-1-13-x-1-15-x-a-better-mailing-system.76442/update?update=329974
